name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Set up environment
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Run tests
        run: |
          poetry run pytest ./tests
